# 区块链浏览器后端服务配置

server:
  host: "0.0.0.0"
  port: 8080
  tls_enabled: true
  tls_port: 8443
  cert_file: "./certs/localhost.crt"
  key_file: "./certs/localhost.key"
  read_timeout: 30s
  write_timeout: 30s
  max_connections: 1000

database:
  driver: "mysql"
  host: "39.106.34.163"
  port: 3306
  username: "blockchain"
  password: "Viruse123!QAZ.."
  dbname: "blockchain_browser"
  max_open_conns: 100
  max_idle_conns: 10
  conn_max_lifetime: 3600s

log:
  level: "info"
  format: "json"
  output: "stdout"
  file:
    enabled: false
    path: "logs/app.log"
    max_size: 100
    max_age: 30
    max_backups: 10

websocket:
  enabled: true
  path: "/ws"
  ping_interval: 30s
  pong_wait: 60s
  write_wait: 10s
  read_buffer_size: 1024
  write_buffer_size: 1024

cors:
  allowed_origins:
    - "*"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allowed_headers:
    - "Origin"
    - "Content-Type"
    - "Content-Length"
    - "Accept-Encoding"
    - "X-CSRF-Token"
    - "Authorization"
  allow_credentials: true
  max_age: 86400

api:
  version: "v1"
  prefix: "/api"
  rate_limit:
    enabled: true
    requests_per_minute: 100
    burst: 20

blockchain:
  verification_timeout: 10s    #取平均时间，如果超过这个时间，则认为区块验证失败
  default_verification_time: 10s  # 基础验证时间（用于动态计算）
  # 动态验证超时配置
  dynamic_verification: true       # 启用动态验证超时
  balance_transaction_count: 200   # 平衡交易数量（200条）
  balance_block_size: 131072       # 平衡区块大小（128KB = 128 * 1024）
  min_verification_time: 5s        # 最小验证时间
  max_verification_time: 20s       # 最大验证时间
  chains:
    btc:
      chain_id: 1
      name: "Bitcoin"
      symbol: "BTC"
      decimals: 8
      enabled: true
      rpc_urls:
        - "https://newest-ultra-friday.btc.quiknode.pro/7091d98af3809c189285739c3f4141b94f368fff"  # JSON-RPC (仅用于获取区块高度)
      rest_urls:
        - "https://blockstream.info/testnet/api"  # REST API (用于获取地址余额)
        - "https://mempool.space/testnet/api"     # REST API (备用)
      username: ""
      password: ""
    eth:
      chain_id: 1       #11155111
      name: "Ethereum"
      symbol: "ETH"
      decimals: 18
      enabled: true
      rpc_urls:
        - "https://alpha-clean-yard.quiknode.pro/7979488c04b1a36bdc4230b23e3eaac3e9c1c1af"
    bsc:
      chain_id: 56      #97
      name: "Binance Smart Chain Testnet"
      symbol: "BSC"
      decimals: 18
      enabled: true
      rpc_urls:
        - "https://yolo-smart-tree.bsc.quiknode.pro/52836b8f979fca7325258c42925d6c245ca45079"  # JSON-RPC (仅用于获取区块高度)
    sol:
      chain_id: 101
      name: "Solana"
      symbol: "SOL"
      decimals: 9
      enabled: true
      rpc_urls:
        - "https://thrilling-summer-frost.solana-mainnet.quiknode.pro/ca8e71700184f645a7935acf1487acd191e429a1"

cache:
  enabled: false
  driver: "memory"
  redis:
    host: "localhost"
    port: 6379
    password: ""
    db: 0
    pool_size: 10

security:
  jwt_secret: "blockchain-browser-secret-key"
  jwt_expiration: 24h
  bcrypt_cost: 12

# 数据清理配置 尽量使用素数（可以避免因为除数相同导致清理间隔相同）3, 5, 7, 11, 13, 17, 19, 83, 89, 97
data_cleanup:
  eth:
    max_blocks: 1000        # ETH最大保留区块数
    cleanup_threshold: 2000 # ETH清理阈值
    batch_size: 10000         # ETH批量删除大小
    interval: 17             # ETH清理间隔（分钟）
  btc:
    max_blocks: 1000         # BTC最大保留区块数
    cleanup_threshold: 2000  # BTC清理阈值
    batch_size: 10000          # BTC批量删除大小
    interval: 97            # BTC清理间隔（分钟） 
  bsc:
    max_blocks: 500        # BSC最大保留区块数
    cleanup_threshold: 1000 # BSC清理阈值
    batch_size: 10000         # BSC批量删除大小
    interval: 7             # BSC清理间隔（分钟）
  sol:
    max_blocks: 500        # SOL最大保留区块数
    cleanup_threshold: 1000 # SOL清理阈值
    batch_size: 10000         # SOL批量删除大小
    interval: 3             # SOL清理间隔（分钟）