# 区块链浏览器后端服务配置

server:
  host: "0.0.0.0"
  port: 8080
  tls_enabled: true
  tls_port: 8443
  cert_file: "./certs/localhost.crt"
  key_file: "./certs/localhost.key"
  read_timeout: 30s
  write_timeout: 30s
  max_connections: 1000

database:
  driver: "mysql"
  host: "127.0.0.1"
  port: 3306
  username: "root"
  password: "123"
  dbname: "blockchain_browser"
  max_open_conns: 100
  max_idle_conns: 10
  conn_max_lifetime: 3600s

log:
  level: "info"
  format: "json"
  output: "stdout"
  file:
    enabled: false
    path: "logs/app.log"
    max_size: 100
    max_age: 30
    max_backups: 10

websocket:
  enabled: true
  path: "/ws"
  ping_interval: 30s
  pong_wait: 60s
  write_wait: 10s
  read_buffer_size: 1024
  write_buffer_size: 1024

cors:
  allowed_origins:
    - "*"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allowed_headers:
    - "Origin"
    - "Content-Type"
    - "Content-Length"
    - "Accept-Encoding"
    - "X-CSRF-Token"
    - "Authorization"
  allow_credentials: true
  max_age: 86400

api:
  version: "v1"
  prefix: "/api"
  rate_limit:
    enabled: true
    requests_per_minute: 100
    burst: 20

blockchain:
  verification_timeout: 10s    #取平均时间，如果超过这个时间，则认为区块验证失败
  default_verification_time: 10s  # 基础验证时间（用于动态计算）
  # 动态验证超时配置
  dynamic_verification: true       # 启用动态验证超时
  balance_transaction_count: 200   # 平衡交易数量（200条）
  balance_block_size: 131072       # 平衡区块大小（128KB = 128 * 1024）
  min_verification_time: 5s        # 最小验证时间
  max_verification_time: 20s       # 最大验证时间
  chains:
    btc:
      chain_id: 0
      name: "Bitcoin"
      symbol: "BTC"
      decimals: 8
      enabled: true
      rpc_urls:
        - "http://127.0.0.1:8332"
      username: "bitcoin"
      password: "bitcoin123"
    eth:
      chain_id: 11155111
      name: "Ethereum"
      symbol: "ETH"
      decimals: 18
      enabled: true
      rpc_urls:
        - "https://alpha-clean-yard.ethereum-sepolia.quiknode.pro/7979488c04b1a36bdc4230b23e3eaac3e9c1c1af"
        - "https://newest-ultra-friday.ethereum-sepolia.quiknode.pro/7091d98af3809c189285739c3f4141b94f368fff"
        - "https://yolo-smart-tree.ethereum-sepolia.quiknode.pro/52836b8f979fca7325258c42925d6c245ca45079"
        - "https://thrilling-summer-frost.ethereum-sepolia.quiknode.pro/ca8e71700184f645a7935acf1487acd191e429a1"
        - "https://warmhearted-bold-emerald.ethereum-sepolia.quiknode.pro/be4e6633f9443a4dd26046d40be1650a810db3a1"

cache:
  enabled: false
  driver: "memory"
  redis:
    host: "localhost"
    port: 6379
    password: ""
    db: 0
    pool_size: 10

security:
  jwt_secret: "blockchain-browser-secret-key"
  jwt_expiration: 24h
  bcrypt_cost: 12 